# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sum of covariances of squared correlations via \code{RcppArmadillo}.
#'
#' @rdname Cov_r2
#'
#' @importFrom Rcpp evalCpp
#'
Cov_r2A <- function(n, R, E, nthreads = 0L) {
    .Call(`_eigvaldispRcpp_Cov_r2A`, n, R, E, nthreads)
}

#' Sum of covariances of squared correlations
#'
#' @rdname Cov_r2
#' @order 1
#'
Cov_r2C <- function(n, R, E, dummy_nthreads) {
    .Call(`_eigvaldispRcpp_Cov_r2C`, n, R, E, dummy_nthreads)
}

#' Sum of covariances of squared correlations via \code{RcppEigen}.
#'
#' @rdname Cov_r2
#'
#' @importFrom Rcpp evalCpp
#'
Cov_r2E <- function(n, R, E, nthreads = 0L) {
    .Call(`_eigvaldispRcpp_Cov_r2E`, n, R, E, nthreads)
}

#' Sum of covariances of squared correlations via \code{RcppParallel}.
#'
#' @rdname Cov_r2
#'
Cov_r2P <- function(n, R, E, dummy_nthreads) {
    .Call(`_eigvaldispRcpp_Cov_r2P`, n, R, E, dummy_nthreads)
}

